const {
    PORT: port,
    GOOGLE_CLIENT_EMAIL: googleClientEmail,
    GOOGLE_PRIVATE_KEY: googlePrivateKey,
    INTERNAL_SEARCH_SPREADSHEET_ID: internalSearchSpreadsheetId,
    INTERNAL_SEARCH_LISTINGS_SHEET_ID: internalSearchListingsSheetId,
    INTERNAL_SEARCH_LV_ID_SHEET_ID: internalSearchLVIdSheetId,
    ZONE_SPREADSHEET_ID: zoneSpreadsheetId,
    IMAGES_ROOT_SPREADSHEET_ID: imagesRootSpreadsheetId,
    PS_USERNAME: psUsername,
    PS_PASSWORD: psPassword,
    PS_WEB_URL: psWebURL,
    IS_LOCAL: isLocal,
    GOOGLE_CHROME_PATH: googleChromePath,
    FIREBASE_TYPE: firebaseType,
    FIREBASE_PROJECT_ID: firebaseProjectId,
    FIREBASE_PRIVATE_KEY_ID: firebasePrivateKeyId,
    FIREBASE_PRIVATE_KEY: firebasePrivateKey,
    FIREBASE_CLIENT_EMAIL: firebaseClientEmail,
    FIREBASE_CLIENT_ID: firebaseClientId,
    FIREBASE_AUTH_URI: firebaseAuthUri,
    FIREBASE_TOKEN_URI: firebaseTokenUri,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL: firebaseAuthProviderX509CertUrl,
    FIREBASE_CLIENT_X509_CERT_URL: firebaseClientX509CertUrl,
    FIREBASE_UNIVERSE_DOMAIN: firebaseUniverseDomain,
} = process.env

module.exports = {
    port,
    googleClientEmail,
    googlePrivateKey,
    internalSearchSpreadsheetId,
    internalSearchListingsSheetId,
    internalSearchLVIdSheetId,
    zoneSpreadsheetId,
    imagesRootSpreadsheetId,
    psUsername,
    psPassword,
    psWebURL,
    isLocal: isLocal === 'true',
    googleChromePath,
    firebaseType,
    firebaseProjectId,
    firebasePrivateKeyId,
    firebasePrivateKey,
    firebaseClientEmail,
    firebaseClientId,
    firebaseAuthUri,
    firebaseTokenUri,
    firebaseAuthProviderX509CertUrl,
    firebaseClientX509CertUrl,
    firebaseUniverseDomain,
}
