const {JWT} = require("google-auth-library");
const {google} = require("googleapis");
const {googleClientEmail, googlePrivateKey} = require("./environment");

const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    key: googlePrivateKey,
    email: googleClientEmail,
    scopes: [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive"
    ],
});

const drive = google.drive({version: "v3", auth: serviceAccountAuth});

module.exports = {
    serviceAccountAuth,
    drive
}
