import {JWT} from "google-auth-library";
import {google} from "googleapis";
import {googleClientEmail, googlePrivateKey} from "./environment";

export const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    key: googlePrivateKey,
    email: googleClientEmail,
    scopes: [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive"
    ],
});

export const drive = google.drive({version: "v3", auth: serviceAccountAuth});
